-- luacheck antek.lua  (luarocks install luacheck)
std = 'luajit'
max_line_length = false
allow_defined_top = true
globals = { 'main' }
ignore = {
    '431', '432',          -- moduly: A.register((function(A) ... end)(A)) celowo przyslania A / ffi
    '131/main',            -- main() wola MoonLoader
    '211/CYCLE', '411/CYCLE',   -- modul Karty Bot (poza zakresem porzadkow)
}

-- API MoonLoadera / SF.lua (SAMPFUNCS) uzywane w skrypcie
read_globals = {
    "setObjectVisible",
    "setObjectCollision",
    "sampGetVehicleIdByCarHandle",
    "sampSendEnterVehicle",
    "warpCharIntoCar",
    "taskWarpCharIntoCarAsDriver",
    "PLAYER_HANDLE",
    "PLAYER_PED",
    "addBlipForCoord",
    "addEventHandler",
    "addOneOffSound",
    "changeBlipColour",
    "changeBlipDisplay",
    "clearCharTasks",
    "consumeWindowMessage",
    "convert3DCoordsToScreen",
    "createDirectory",
    "doesBlipExist",
    "doesCharExist",
    "doesFileExist",
    "doesObjectExist",
    "doesVehicleExist",
    "getActiveCameraCoordinates",
    "getActiveCameraPointAt",
    "getActiveInterior",
    "getAllObjects",
    "getAllVehicles",
    "getCarCharIsUsing",
    "getCarCoordinates",
    "getCarHeading",
    "getCarModel",
    "getCarSpeed",
    "getCharCoordinates",
    "getCharHeading",
    "getDriverOfCar",
    "getGameDirectory",
    "getGxtText",
    "getNameOfZone",
    "getObjectCoordinates",
    "getObjectHeading",
    "getObjectModel",
    "getObjectPointer",
    "getScreenResolution",
    "getTargetBlipCoordinates",
    "getWorkingDirectory",
    "isCarDead",
    "isCarUpsidedown",
    "isCharDead",
    "isCharInAnyCar",
    "isKeyDown",
    "isKeyJustPressed",
    "isLineOfSightClear",
    "isPauseMenuActive",
    "isPlayerPlaying",
    "isPointOnScreen",
    "isSampAvailable",
    "isSampLoaded",
    "localClock",
    "lua_thread",
    "placeWaypoint",
    "printStringNow",
    "processLineOfSight",
    "removeBlip",
    "renderCreateFont",
    "renderDrawBox",
    "renderDrawLine",
    "renderDrawPolygon",
    "renderFontDrawText",
    "renderGetFontDrawHeight",
    "renderGetFontDrawTextLength",
    "sampAddChatMessage",
    "sampCloseCurrentDialogWithButton",
    "sampGet3dTextInfoById",
    "sampGetCharHandleBySampPlayerId",
    "sampGetChatInputText",
    "sampGetChatString",
    "sampGetCurrentDialogType",
    "sampGetCurrentServerName",
    "sampGetDialogCaption",
    "sampGetDialogText",
    "sampGetLocalPlayerId",
    "sampGetLocalPlayerNickname",
    "sampGetMaxPlayerId",
    "sampGetPlayerColor",
    "sampGetPlayerIdByCharHandle",
    "sampGetPlayerNickname",
    "sampGetPlayerPing",
    "sampIs3dTextDefined",
    "sampIsChatInputActive",
    "sampIsCursorActive",
    "sampIsDialogActive",
    "sampIsPlayerConnected",
    "sampProcessChatInput",
    "sampRegisterChatCommand",
    "sampSendChat",
    "sampSendClickTextdraw",
    "sampSetChatInputEnabled",
    "sampSetChatInputText",
    "sampSetCurrentDialogListItem",
    "sampTextdrawGetBoxEnabledColorAndSize",
    "sampTextdrawGetModelRotationZoomVehColor",
    "sampTextdrawGetPos",
    "sampTextdrawGetString",
    "sampTextdrawGetStyle",
    "sampTextdrawIsExists",
    "script",
    "script_author",
    "script_description",
    "script_name",
    "script_properties",
    "script_version",
    "setCharHeading",
    "setClipboardText",
    "setGameKeyState",
    "storeCarCharIsInNoSave",
    "taskGoStraightToCoord",
    "thisScript",
    "wait",
}

files['tests/'] = { std = 'luajit', globals = { '__ANTEK', 'io', 'os' }, read_globals = { 'unpack' } }
